blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/GabrielCodeProject/payment-integration-template/blob/master/README.md
    about: Check the documentation for usage instructions and guides
  - name: 💬 GitHub Discussions
    url: https://github.com/GabrielCodeProject/payment-integration-template/discussions
    about: Ask questions and discuss features with the community
  - name: 🔒 Private Security Report
    url: https://github.com/GabrielCodeProject/payment-integration-template/security/advisories/new
    about: Report sensitive security vulnerabilities privately
